name: task
description: 待办事项

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  # json 自动注解
  # flutter packages pub run build_runner watch --delete-conflicting-outputs
  # flutter packages pub run build_runner build
  json_annotation: ^3.0.1
  #状态管理 https://github.com/rrousselGit/provider
  provider: ^4.1.3
    # 路由框架 https://github.com/theyakka/fluro
  fluro: ^1.6.0
    # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^2.2.0
    # 网络库 https://github.com/flutterchina/dio
  dio: ^3.0.3
    # https://github.com/ReactiveX/rxdart
  rxdart: ^0.22.4
    # 上拉加载下拉刷新
  flutter_easyrefresh: 2.1.1
  # event bus
  fast_event_bus: ^1.0.1
  # Flutter 轮播图 https://github.com/best-flutter/flutter_swiper
  flutter_swiper: ^1.1.6
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: 0.2.6+1
  # 侧滑删除 https://github.com/letsar/flutter_slidable
  flutter_slidable: ^0.5.4
  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: 0.3.15+1
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^2.1.2
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^2.0.0-rc
  # 启动URL的插件 https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: 5.2.3
  flutter_seekbar:
    git: https://github.com/LiuC520/flutter_seekbar.git
    # 扫码 https://github.com/apptreesoftware/flutter_barcode_reader
  barcode_scan:
    git:
      url: https://github.com/simplezhli/flutter_barcode_reader.git
  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^4.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  # json 自动注解
  build_runner: ^1.7.2
  json_serializable: ^3.3.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/support/
    - assets/images/english/
    - assets/images/todo/
    - assets/images/suitcase/
    - assets/images/currency/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
